---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterworkloads.example.com
spec:
  group: example.com
  names:
    kind: ClusterWorkload
    listKind: ClusterWorkloadList
    plural: clusterworkloads
    singular: clusterworkload
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WorkloadSpec defines the desired state of Workload
            properties:
              hostname:
                description: The hostname used to identify the workload.
                type: string
              additionalHostnames:
                description: Additional hostnames used to identify the workload.
                items:
                  type: string
                type: array
            type: object
          status:
            description: WorkloadStatus defines the observed state of Workload
            properties:
              addr:
                description: The address at which the workload can be reached.
                type: string
              additionalAddrs:
                description: Additional addresses at which the workload can be reached.
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
